source 'https://rubygems.org/'
#ruby '1.9.3'
gem 'rails', '3.2.11'


gem 'mongoid'
gem 'bson_ext'
gem "paperclip"
gem "mongoid-paperclip", :require => "mongoid_paperclip" 
gem 'aws-sdk'

gem "mongo_mapper"
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'jquery-rails'
gem 'devise'

# rspec testing gems 
group :development, :test do
  gem 'rspec-rails','~>3.0.0.beta'
  gem 'factory_girl_rails'
end

#handle sorting of tabels for more info go to this link https://github.com/dadooda/handles_sortable_columns
gem "handles_sortable_columns"

# (GUI Team) Gems to handle bootstrap
gem 'therubyracer'   # require JS runtime.
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'formtastic'
gem 'formtastic-bootstrap' 
#This gem used to translate an address String to real coordinates of this place or vice versa
gem 'geocoder', '~> 1.2.0' 
#This gem used to help in intialising a map
gem 'gmaps4rails', '~> 2.1.2' 
#This gem used to pass values from rails controler to javascript
#handles the pop up message in the member_item_index_page "go shopping"
gem "gon" , '5.0.4'
#handles the showen progress bar 
gem 'css3-progress-bar-rails'



gem 'prawn'
gem 'prawn-print'

gem 'rspec'
gem 'prawnto_2', :require => 'prawnto'
#gem 'rspec-rails', '~> 2.0'
gem 'capybara'
gem 'pdf-inspector'
gem 'webmock'


gem 'pdf-reader', :require => 'pdf/reader'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
